twitter/urls.py
from django.conf.urls import url
from . import views

app_name = 'twitter'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^status/$', views.process, name='process'),
]

twitter_kafka/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^twitter/', include('twitter.urls')),
    url(r'^admin/', admin.site.urls),
]

twitter/models.py
import uuid
from cassandra.cqlengine import columns
from django_cassandra_engine.models import DjangoCassandraModel


class TweetModel(DjangoCassandraModel):
    tweet_id = columns.UUID(primary_key=True, default=uuid.uuid4)
    user_name = columns.Text(index=True)
    tweet_text = columns.Text(required=True)
    user_location = columns.Text(required=False)
    verified_user = columns.Boolean(required=False)


class Topic(DjangoCassandraModel):
    topic = columns.Text(primary_key=True)

twitter/forms.py
from django import forms

from .models import Topic


class TopicForm(forms.ModelForm):
	topic = forms.CharField(max_length=128)

	class Meta:
		model = Topic
		fields = ('topic',)
		

twitter/views.py
from django.shortcuts import render
from twitter.forms import TopicForm
from django.http import HttpResponse
from .twitter_handler import TwitterAccess


def index(request):
    form = TopicForm(request.POST)
    return render(request, 'twitter/topic.html', {'form': form})


# Create your views here.
def process(request):
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            search_topic = form.cleaned_data['topic']
            TwitterAccess.get_stream(search_topic)
            return HttpResponse("Topic created successfully!!")
    else:
        return HttpResponse("Only POST is supported")

    return HttpResponse("Error")

twitter/templates/twitter/topic.html
<!DOCTYPE html>
<html>
    <head>
        <title>Kafka - Twitter App</title>
    </head>

    <body>
        <h1>Kafka - Twitter App</h1>
        <h3>Enter a search term</h3>

        <form id="topic_form" method="post" action="{% url 'twitter:process' %}">

            {% csrf_token %}
            

            {% for field in form.visible_fields %}
                {{ field }}
            {% endfor %}

            <input type="submit" name="Create Topic" value="Create Topic" />
        </form>
    </body>

</html>